### ISSUE TITLE
results empty

### ISSUE THREAD

**Issue by ghost** [zhengziqiang/ReshapeGAN#3]
I ran main.py 
WARNING:tensorflow:From /content/ReshapeGAN/ops.py:25: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d_transpose instead.
 [*] Reading checkpoints...
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
 [*] Success to read model-500001
 [*] Load SUCCESS
 [*] Test finished!

and results dir is empty, no result images

**Comment by zhengziqiang** [comment]
test_path = os.path.join(self.dataset, 'combination')
check_folder(test_path)

Please make sure that  the combination directory is at the right place. Maybe there are something wrong. I will fix it soon.

**Comment by zhengziqiang** [comment]
Sorry, I made a mistake, I have fixed it. @ak9250

**Comment by ghost** [comment]
I tried it again and it is still showing as empty results directory, also how can you test with single reference image?
